# Generated by Django 3.2 on 2021-04-14 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_myuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='username',
        ),
    ]
